# Generated by Django 3.2.8 on 2022-07-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Clente')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('RUC', models.IntegerField(verbose_name='RUC')),
                ('DNI', models.CharField(max_length=8, verbose_name='DNI')),
                ('encargado', models.CharField(max_length=20, verbose_name='Encargado')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('Nro_orden', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro Orden')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha Salida')),
            ],
        ),
        migrations.CreateModel(
            name='Soldadora',
            fields=[
                ('id_soldadora', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Soldadora')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('Nro_serie', models.CharField(max_length=40, verbose_name='Nro. Serie')),
                ('code', models.CharField(max_length=40, verbose_name='Code')),
                ('horometro', models.CharField(max_length=40, verbose_name='Horometro')),
                ('diagnostico', models.CharField(max_length=120, verbose_name='Diagnostico')),
                ('foto_ingreso', models.ImageField(null=True, upload_to='fotos/', verbose_name='Imagen Ingreso')),
                ('foto_reparacion', models.ImageField(null=True, upload_to='fotos/', verbose_name='Imagen Reparacion')),
                ('foto_salida', models.ImageField(null=True, upload_to='fotos/', verbose_name='Imagen Salida')),
                ('Nro_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.orden', verbose_name='Nro Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Planchado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_p', models.IntegerField(verbose_name='Cod. Producto')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('Nro_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.orden', verbose_name='Nro Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('receptor', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Recepcionado Por')),
                ('servicio', models.CharField(max_length=40, verbose_name='Servicio')),
                ('falla', models.CharField(max_length=100, verbose_name='falla')),
                ('Nro_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.orden', verbose_name='Nro Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antorcha', models.BooleanField(verbose_name='Antorcha')),
                ('portaelectrodo', models.BooleanField(verbose_name='Porta Electrodo')),
                ('pinza_masa', models.BooleanField(verbose_name='Pinza Masa')),
                ('cable_acometida', models.BooleanField(verbose_name='Cable Acometida')),
                ('clavija', models.BooleanField(verbose_name='Clavija')),
                ('regulador_gas', models.BooleanField(verbose_name='Regulador de Gas')),
                ('manguera_gas', models.BooleanField(verbose_name='Manguera de Gas')),
                ('pernos', models.BooleanField(verbose_name='Pernos')),
                ('ridillos', models.BooleanField(verbose_name='Ridillos')),
                ('perillas', models.BooleanField(verbose_name='Perillas')),
                ('asas', models.BooleanField(verbose_name='Asas')),
                ('bases_ruedas', models.BooleanField(verbose_name='Base de Ruedas')),
                ('carrete', models.BooleanField(verbose_name='Carrete')),
                ('consumibles', models.BooleanField(verbose_name='Consumibles')),
                ('chupon_o_conductor', models.BooleanField(verbose_name='Chupón o Conductor')),
                ('otros', models.BooleanField(verbose_name='Otros')),
                ('Nro_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.orden', verbose_name='Nro Orden')),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente', verbose_name='Id Cliente')),
                ('id_soldadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.soldadora', verbose_name='Id Soldadora')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Nro_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.orden', verbose_name='Nro Orden'),
        ),
    ]
