/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import config.Conexion;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Formulario extends javax.swing.JFrame{
    Conexion cn = new Conexion();
    Connection con;
    Statement st;
    ResultSet rs;
    int Nro_Orden = 17;
    String Ruta = "";
    String Ruta2 = "";
    String Ruta3 = "";
    
    //Inicio Inicio=new Inicio();

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesantorcha = new javax.swing.ButtonGroup();
        botonesportaelectrodo = new javax.swing.ButtonGroup();
        botonespinzamasa = new javax.swing.ButtonGroup();
        botonescableacometida = new javax.swing.ButtonGroup();
        botonesclavija = new javax.swing.ButtonGroup();
        botonesreguladorgas = new javax.swing.ButtonGroup();
        botonesmangueragas = new javax.swing.ButtonGroup();
        botonespernos = new javax.swing.ButtonGroup();
        botonesridillos = new javax.swing.ButtonGroup();
        botonesperillas = new javax.swing.ButtonGroup();
        botonesasas = new javax.swing.ButtonGroup();
        botonesbaseruedas = new javax.swing.ButtonGroup();
        botonescarrete = new javax.swing.ButtonGroup();
        botonesconsumibles = new javax.swing.ButtonGroup();
        botoneschupon = new javax.swing.ButtonGroup();
        botonesotros = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        LabelFechaIngreso = new javax.swing.JLabel();
        txtFechaSalida = new com.toedter.calendar.JDateChooser();
        LabelFechaSalida = new javax.swing.JLabel();
        LabelOrden = new javax.swing.JLabel();
        LabelNro = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        txtEncargado = new javax.swing.JTextField();
        LabelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        LabelMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        LabelModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        LabelCode = new javax.swing.JLabel();
        LabelHorometro = new javax.swing.JLabel();
        txtHorometro = new javax.swing.JTextField();
        LabelNroSerie = new javax.swing.JLabel();
        LabelReceptor = new javax.swing.JLabel();
        txtReceptor = new javax.swing.JTextField();
        LabelServicio = new javax.swing.JLabel();
        CheckBoxGarantia = new javax.swing.JCheckBox();
        CheckBoxReparacion = new javax.swing.JCheckBox();
        CheckBoxMantenimento = new javax.swing.JCheckBox();
        CheckBoxReclamo = new javax.swing.JCheckBox();
        LabelFalla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFallaReportada = new javax.swing.JTextArea();
        LabelFotoIngreso = new javax.swing.JLabel();
        LabelFotoReparacion = new javax.swing.JLabel();
        LabelFotoSalida = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        btnReparacion = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        LabelCliente = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        LabelDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        LabelRUC = new javax.swing.JLabel();
        LabelDNI = new javax.swing.JLabel();
        LabelPlanchado = new javax.swing.JLabel();
        LabelEncargado = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePlanchado = new javax.swing.JTable();
        txtDNI = new javax.swing.JTextField();
        txt_NroSerie = new javax.swing.JTextField();
        labelReparacion = new javax.swing.JLabel();
        labelSalida = new javax.swing.JLabel();
        labelIngreso = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        LabelElementos1 = new javax.swing.JLabel();
        LabelElementos2 = new javax.swing.JLabel();
        LabelAntorcha = new javax.swing.JLabel();
        LabelPortaElectrodo = new javax.swing.JLabel();
        RadioPortaSi = new javax.swing.JRadioButton();
        RadioPortaNo = new javax.swing.JRadioButton();
        LabelPinza = new javax.swing.JLabel();
        RadioPinzaSi = new javax.swing.JRadioButton();
        RadioPinzaNo = new javax.swing.JRadioButton();
        LabelCableAcometica = new javax.swing.JLabel();
        RadioCableSi = new javax.swing.JRadioButton();
        RadioCableNo = new javax.swing.JRadioButton();
        LabelClavija = new javax.swing.JLabel();
        RadioClavijaSi = new javax.swing.JRadioButton();
        RadioClavijaNo = new javax.swing.JRadioButton();
        LabelReguladorGas = new javax.swing.JLabel();
        RadioReguladorSi = new javax.swing.JRadioButton();
        RadioReguladorNo = new javax.swing.JRadioButton();
        LabelManguera = new javax.swing.JLabel();
        RadioMangueraSi = new javax.swing.JRadioButton();
        RadioMangueraNo = new javax.swing.JRadioButton();
        LabelPernos = new javax.swing.JLabel();
        RadioPernosSi = new javax.swing.JRadioButton();
        RadioPernosNo = new javax.swing.JRadioButton();
        LabelRidillos = new javax.swing.JLabel();
        RadioRidillosSi = new javax.swing.JRadioButton();
        RadioRidillosNo = new javax.swing.JRadioButton();
        LabelPerillas = new javax.swing.JLabel();
        RadioPerillasSi = new javax.swing.JRadioButton();
        RadioPerillasNo = new javax.swing.JRadioButton();
        LabelAsas = new javax.swing.JLabel();
        RadioAsasSi = new javax.swing.JRadioButton();
        RadioAsasNo = new javax.swing.JRadioButton();
        LabelBaseRuedas = new javax.swing.JLabel();
        RadioRuedasSi = new javax.swing.JRadioButton();
        RadioRuedasNo = new javax.swing.JRadioButton();
        LabelCarrete = new javax.swing.JLabel();
        RadioCarreteSi = new javax.swing.JRadioButton();
        RadioCarreteNo = new javax.swing.JRadioButton();
        LabelOtros = new javax.swing.JLabel();
        RadioConsumiblesSi = new javax.swing.JRadioButton();
        RadioConsumiblesNo = new javax.swing.JRadioButton();
        LabelChupon = new javax.swing.JLabel();
        RadioChuponSi = new javax.swing.JRadioButton();
        RadioChuponNo = new javax.swing.JRadioButton();
        LabelDiagnostico = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableDiagnostico = new javax.swing.JTable();
        LabelConsumibles = new javax.swing.JLabel();
        RadioOtrosSi = new javax.swing.JRadioButton();
        RadioOtrosNo = new javax.swing.JRadioButton();
        RadioAntorchaNo = new javax.swing.JRadioButton();
        RadioAntorchaSi = new javax.swing.JRadioButton();
        txtAntorcha = new javax.swing.JTextField();
        txtPortaElectrodo = new javax.swing.JTextField();
        txtPinzaMasa = new javax.swing.JTextField();
        txtCableAcometida = new javax.swing.JTextField();
        txtClavija = new javax.swing.JTextField();
        txtReguladorGas = new javax.swing.JTextField();
        txtMangueraGas = new javax.swing.JTextField();
        txtPernos = new javax.swing.JTextField();
        txtPerillas = new javax.swing.JTextField();
        txtRidillos = new javax.swing.JTextField();
        txtAsas = new javax.swing.JTextField();
        txtBasedeRuedas = new javax.swing.JTextField();
        txtCarrete = new javax.swing.JTextField();
        txtConsumibles = new javax.swing.JTextField();
        txtChupon = new javax.swing.JTextField();
        txtOtros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtNroOrden = new javax.swing.JTextField();

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Volver.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFechaIngreso.setDateFormatString("yyyy-MM-dd");

        LabelFechaIngreso.setText("FECHA DE INGRESO:");

        txtFechaSalida.setDateFormatString("yyyy-MM-dd");

        LabelFechaSalida.setText("FECHA DE SALIDA:");

        LabelOrden.setText("ORDEN DE SERVICIO");

        LabelNro.setText("N°");

        LabelTelefono.setText("TELEFONO:");

        LabelMarca.setText("MARCA:");

        LabelEmail.setText("E-MAIL:");

        LabelModelo.setText("MODELO:");

        LabelCode.setText("CODE:");

        LabelHorometro.setText("HOROMETRO:");

        LabelNroSerie.setText("N° SERIE:");

        LabelReceptor.setText("RECEPCIONADO POR:");

        LabelServicio.setText("SERVICIO SOLICITADO:");

        CheckBoxGarantia.setText("GARANTÍA");

        CheckBoxReparacion.setText("REPARACIÓN");

        CheckBoxMantenimento.setText("MANTENIMIENTO");

        CheckBoxReclamo.setText("RECLAMO");

        LabelFalla.setText("FALLA REPORTADA POR EL CLIENTE:");

        txtFallaReportada.setColumns(20);
        txtFallaReportada.setRows(5);
        jScrollPane1.setViewportView(txtFallaReportada);

        LabelFotoIngreso.setText("FOTO INGRESO:");

        LabelFotoReparacion.setText("FOTO REPARACION:");

        LabelFotoSalida.setText("FOTO SALIDA:");

        btnIngreso.setText("SUBIR");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        btnReparacion.setText("SUBIR");
        btnReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReparacionActionPerformed(evt);
            }
        });

        btnSalida.setText("SUBIR");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        LabelCliente.setText("CLIENTE:");

        LabelDireccion.setText("DIRECCIÓN:");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        LabelRUC.setText("RUC:");

        LabelDNI.setText("DNI:");

        LabelPlanchado.setText("SALIDA PARA PLANCHADO Y PINTURA");

        LabelEncargado.setText("ENCARGADO:");

        TablePlanchado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD. P", "CANT.", "DESCRIPCION"
            }
        ));
        jScrollPane2.setViewportView(TablePlanchado);

        txtServicio.setEditable(false);
        txtServicio.setText("jTextField1");

        jLabel1.setText("COD.P");

        jLabel2.setText("CANT.");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("DESCRIPCIÓN");

        jButton3.setText("AGREGAR");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(LabelEncargado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRUC, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtEncargado)))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelMarca)
                                            .addComponent(LabelModelo))
                                        .addGap(27, 27, 27))
                                    .addComponent(LabelHorometro, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(6, 6, 6)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHorometro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDNI)
                                    .addComponent(LabelTelefono)
                                    .addComponent(LabelEmail)
                                    .addComponent(LabelCode))
                                .addGap(10, 10, 10)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCode)
                                    .addComponent(txtDNI)))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(LabelNroSerie)
                                .addGap(18, 18, 18)
                                .addComponent(txt_NroSerie))))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(LabelFalla)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(LabelServicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckBoxGarantia)
                                .addGap(6, 6, 6)
                                .addComponent(CheckBoxReparacion)
                                .addGap(22, 22, 22)
                                .addComponent(CheckBoxMantenimento)
                                .addGap(29, 29, 29)
                                .addComponent(CheckBoxReclamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(LabelReceptor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReceptor))))
                    .addComponent(LabelRUC)
                    .addComponent(LabelPlanchado)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCliente)
                            .addComponent(LabelDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtDireccion)))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnIngreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(LabelFotoIngreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelFotoReparacion)))
                        .addGap(108, 108, 108)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(btnSalida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelFotoSalida)))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReparacion)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCliente)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRUC)
                    .addComponent(LabelDNI)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEncargado)
                    .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHorometro)
                    .addComponent(txtHorometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNroSerie)
                    .addComponent(txt_NroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelReceptor)
                    .addComponent(txtReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelServicio)
                    .addComponent(CheckBoxGarantia)
                    .addComponent(CheckBoxReparacion)
                    .addComponent(CheckBoxMantenimento)
                    .addComponent(CheckBoxReclamo)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelFalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFotoIngreso)
                            .addComponent(LabelFotoReparacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReparacion)
                            .addComponent(labelReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LabelFotoSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIngreso))
                            .addComponent(btnSalida))))
                .addGap(7, 7, 7)
                .addComponent(LabelPlanchado)
                .addGap(9, 9, 9)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel46.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel46.setText("ORDEN DE SERVICIO");

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Volver.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        LabelElementos1.setText("ELEMENTOS DE LOS EQUIPOS");

        LabelElementos2.setText("ELEMENTOS DE LOS EQUIPOS");

        LabelAntorcha.setText("ANTORCHA");

        LabelPortaElectrodo.setText("PORTAELECTRODO");

        botonesportaelectrodo.add(RadioPortaSi);
        RadioPortaSi.setText("SI");
        RadioPortaSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPortaSiActionPerformed(evt);
            }
        });

        botonesportaelectrodo.add(RadioPortaNo);
        RadioPortaNo.setText("NO");

        LabelPinza.setText("PINZA MASA");

        botonespinzamasa.add(RadioPinzaSi);
        RadioPinzaSi.setText("SI");

        botonespinzamasa.add(RadioPinzaNo);
        RadioPinzaNo.setText("NO");

        LabelCableAcometica.setText("CABLE ACOMETIDA");

        botonescableacometida.add(RadioCableSi);
        RadioCableSi.setText("SI");

        botonescableacometida.add(RadioCableNo);
        RadioCableNo.setText("NO");

        LabelClavija.setText("CLAVIJA");

        botonesclavija.add(RadioClavijaSi);
        RadioClavijaSi.setText("SI");

        botonesclavija.add(RadioClavijaNo);
        RadioClavijaNo.setText("NO");

        LabelReguladorGas.setText("REGULADOR DE GAS");

        botonesreguladorgas.add(RadioReguladorSi);
        RadioReguladorSi.setText("SI");

        botonesreguladorgas.add(RadioReguladorNo);
        RadioReguladorNo.setText("NO");

        LabelManguera.setText("MANGUERA DE GAS");

        botonesmangueragas.add(RadioMangueraSi);
        RadioMangueraSi.setText("SI");

        botonesmangueragas.add(RadioMangueraNo);
        RadioMangueraNo.setText("NO");

        LabelPernos.setText("PERNOS");

        botonespernos.add(RadioPernosSi);
        RadioPernosSi.setText("SI");

        botonespernos.add(RadioPernosNo);
        RadioPernosNo.setText("NO");

        LabelRidillos.setText("RIDILLOS");

        botonesridillos.add(RadioRidillosSi);
        RadioRidillosSi.setText("SI");

        botonesridillos.add(RadioRidillosNo);
        RadioRidillosNo.setText("NO");

        LabelPerillas.setText("PERILLAS");

        botonesperillas.add(RadioPerillasSi);
        RadioPerillasSi.setText("SI");

        botonesperillas.add(RadioPerillasNo);
        RadioPerillasNo.setText("NO");

        LabelAsas.setText("ASAS");

        botonesasas.add(RadioAsasSi);
        RadioAsasSi.setText("SI");

        botonesasas.add(RadioAsasNo);
        RadioAsasNo.setText("NO");

        LabelBaseRuedas.setText("BASE DE RUEDAS");

        botonesbaseruedas.add(RadioRuedasSi);
        RadioRuedasSi.setText("SI");

        botonesbaseruedas.add(RadioRuedasNo);
        RadioRuedasNo.setText("NO");

        LabelCarrete.setText("CARRETE");

        botonescarrete.add(RadioCarreteSi);
        RadioCarreteSi.setText("SI");

        botonescarrete.add(RadioCarreteNo);
        RadioCarreteNo.setText("NO");

        LabelOtros.setText("OTROS");

        botonesconsumibles.add(RadioConsumiblesSi);
        RadioConsumiblesSi.setText("SI");

        botonesconsumibles.add(RadioConsumiblesNo);
        RadioConsumiblesNo.setText("NO");

        LabelChupon.setText("CHUPÓN O CONDUCTOR");

        botoneschupon.add(RadioChuponSi);
        RadioChuponSi.setText("SI");

        botoneschupon.add(RadioChuponNo);
        RadioChuponNo.setText("NO");

        LabelDiagnostico.setText("DIAGNOSTICO");

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane4.setViewportView(txtDiagnostico);

        TableDiagnostico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD. P", "CANT.", "DESCRIPCION"
            }
        ));
        jScrollPane3.setViewportView(TableDiagnostico);

        LabelConsumibles.setText("CONSUMIBLES");

        botonesotros.add(RadioOtrosSi);
        RadioOtrosSi.setText("SI");

        botonesotros.add(RadioOtrosNo);
        RadioOtrosNo.setText("NO");
        RadioOtrosNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RadioOtrosNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOtrosNoActionPerformed(evt);
            }
        });

        botonesantorcha.add(RadioAntorchaNo);
        RadioAntorchaNo.setText("NO");

        botonesantorcha.add(RadioAntorchaSi);
        RadioAntorchaSi.setText("SI");

        txtAntorcha.setEditable(false);

        txtPortaElectrodo.setEditable(false);

        txtPinzaMasa.setEditable(false);

        txtCableAcometida.setEditable(false);

        txtClavija.setEditable(false);

        txtReguladorGas.setEditable(false);

        txtMangueraGas.setEditable(false);

        txtPernos.setEditable(false);

        txtPerillas.setEditable(false);

        txtRidillos.setEditable(false);
        txtRidillos.setMinimumSize(new java.awt.Dimension(0, 20));

        txtAsas.setEditable(false);

        txtBasedeRuedas.setEditable(false);

        txtCarrete.setEditable(false);

        txtConsumibles.setEditable(false);

        txtChupon.setEditable(false);

        txtOtros.setEditable(false);

        jLabel4.setText("COD.P");

        jLabel5.setText("CANT.");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel6.setText("DESCRIPCIÓN");

        jButton4.setText("AGREGAR");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPernos)
                    .addComponent(txtMangueraGas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtReguladorGas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtClavija, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCableAcometida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPinzaMasa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPortaElectrodo)
                    .addComponent(txtAntorcha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRidillos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAntorcha)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(LabelElementos1)))
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(LabelElementos2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtChupon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtConsumibles, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCarrete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBasedeRuedas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAsas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(txtPerillas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addComponent(LabelCarrete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RadioCarreteSi))
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addComponent(LabelConsumibles)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RadioConsumiblesSi))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                        .addComponent(LabelChupon)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioChuponSi))
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelAsas)
                                            .addComponent(LabelBaseRuedas)
                                            .addComponent(LabelOtros)
                                            .addComponent(LabelPerillas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RadioRuedasSi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RadioAsasSi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RadioPerillasSi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RadioOtrosSi, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addComponent(RadioPerillasNo)
                                        .addContainerGap(30, Short.MAX_VALUE))
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RadioChuponNo)
                                            .addComponent(RadioConsumiblesNo)
                                            .addComponent(RadioCarreteNo)
                                            .addComponent(RadioRuedasNo)
                                            .addComponent(RadioAsasNo)
                                            .addComponent(RadioOtrosNo))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelPinza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioPinzaSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioPinzaNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelCableAcometica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioCableSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioCableNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelClavija)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioClavijaSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioClavijaNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelReguladorGas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(RadioReguladorSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioReguladorNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelManguera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioMangueraSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioMangueraNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelRidillos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioRidillosSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioRidillosNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                                .addComponent(LabelPernos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioPernosSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioPernosNo))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(LabelPortaElectrodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addComponent(RadioAntorchaSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioAntorchaNo))
                                    .addGroup(Panel2Layout.createSequentialGroup()
                                        .addComponent(RadioPortaSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioPortaNo)))))
                        .addContainerGap(303, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDiagnostico)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Panel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane4)
                            .addGap(10, 10, 10))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                            .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton4)))
                            .addContainerGap()))))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelElementos1)
                    .addComponent(LabelElementos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioAntorchaSi)
                        .addComponent(RadioAntorchaNo))
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelAntorcha)
                        .addComponent(LabelPerillas)
                        .addComponent(RadioPerillasNo)
                        .addComponent(RadioPerillasSi)
                        .addComponent(txtAntorcha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPerillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPortaElectrodo)
                    .addComponent(RadioPortaSi)
                    .addComponent(RadioPortaNo)
                    .addComponent(LabelAsas)
                    .addComponent(RadioAsasSi)
                    .addComponent(RadioAsasNo)
                    .addComponent(txtPortaElectrodo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPinza)
                    .addComponent(RadioPinzaSi)
                    .addComponent(RadioPinzaNo)
                    .addComponent(LabelBaseRuedas)
                    .addComponent(RadioRuedasSi)
                    .addComponent(RadioRuedasNo)
                    .addComponent(txtPinzaMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasedeRuedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCableAcometica)
                    .addComponent(RadioCableSi)
                    .addComponent(RadioCableNo)
                    .addComponent(LabelCarrete)
                    .addComponent(RadioCarreteSi)
                    .addComponent(RadioCarreteNo)
                    .addComponent(txtCableAcometida, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelClavija)
                    .addComponent(RadioClavijaSi)
                    .addComponent(RadioClavijaNo)
                    .addComponent(RadioConsumiblesSi)
                    .addComponent(RadioConsumiblesNo)
                    .addComponent(LabelConsumibles)
                    .addComponent(txtClavija, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsumibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelReguladorGas)
                    .addComponent(RadioReguladorSi)
                    .addComponent(RadioReguladorNo)
                    .addComponent(LabelChupon)
                    .addComponent(RadioChuponSi)
                    .addComponent(RadioChuponNo)
                    .addComponent(txtReguladorGas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelManguera)
                    .addComponent(RadioMangueraSi)
                    .addComponent(RadioMangueraNo)
                    .addComponent(LabelOtros)
                    .addComponent(RadioOtrosSi)
                    .addComponent(RadioOtrosNo)
                    .addComponent(txtMangueraGas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPernos)
                    .addComponent(RadioPernosSi)
                    .addComponent(RadioPernosNo)
                    .addComponent(txtPernos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRidillos)
                    .addComponent(RadioRidillosSi)
                    .addComponent(RadioRidillosNo)
                    .addComponent(txtRidillos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelDiagnostico)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNroOrden.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFechaIngreso)
                            .addComponent(LabelFechaSalida))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelNro)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNroOrden))
                        .addGap(30, 30, 30)
                        .addComponent(btnVolver)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelFechaIngreso)
                                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelFechaSalida)))
                            .addComponent(jLabel46))
                        .addGap(4, 4, 4))
                    .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelOrden)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNro)
                            .addComponent(txtNroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioOtrosNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOtrosNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioOtrosNoActionPerformed

    private void RadioPortaSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPortaSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioPortaSiActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio Inicio=new Inicio();
        Inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Agregarorden();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Ruta = fileChooser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(Ruta).getImage();
            labelIngreso.setText("Subido");
        }
    }//GEN-LAST:event_btnIngresoActionPerformed
    private byte[] getImagen(String Ruta) {
        File imagen = new File(Ruta);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;
        } catch (Exception ex) {
            return null;
        }
    }
    private void btnReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReparacionActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Ruta2 = fileChooser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(Ruta2).getImage();
            labelReparacion.setText("Subido");
        }
    }//GEN-LAST:event_btnReparacionActionPerformed
    private byte[] getImagen2(String Ruta2) {
        File imagen = new File(Ruta2);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;
        } catch (Exception ex) {
            return null;
        }
    }
    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Ruta3 = fileChooser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(Ruta3).getImage();
            labelSalida.setText("Subido");
        }
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    
    private byte[] getImagen3(String Ruta3) {
        File imagen = new File(Ruta3);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;
        } catch (Exception ex) {
            return null;
        }
    }
    
    void Agregarorden() {
                
        String fechaInicio =((JTextField)txtFechaIngreso.getDateEditor().getUiComponent()).getText();
        String fechaSalida =((JTextField)txtFechaSalida.getDateEditor().getUiComponent()).getText();
        
        String Nombre = txtNombre.getText();
        String Direccion = txtDireccion.getText();
        String RUC = txtRUC.getText();
        String DNI = txtDNI.getText();
        String Encargado = txtEncargado.getText();
        String Telefono = txtTelefono.getText();
        
        String Marca = txtMarca.getText();
        String Email = txtEmail.getText();
        String Modelo = txtModelo.getText();
        String Code = txtCode.getText();
        String Horometro = txtHorometro.getText();
        String Nro_Serie = txt_NroSerie.getText();
        
        
        String Recepcionado_por = txtReceptor.getText();
        if(CheckBoxGarantia.isSelected() && CheckBoxReparacion.isSelected()  && CheckBoxMantenimento.isSelected() && CheckBoxReclamo.isSelected()){
            JOptionPane.showMessageDialog(null, "No puede Seleccionar Todos");               
        }
         if(CheckBoxGarantia.isSelected() && CheckBoxReparacion.isSelected()){
            JOptionPane.showMessageDialog(null, "Seleccione solo Uno");               
        }
        if(CheckBoxReparacion.isSelected()  && CheckBoxMantenimento.isSelected()){
            JOptionPane.showMessageDialog(null, "Seleccione solo Uno");               
        }
        if(CheckBoxMantenimento.isSelected() && CheckBoxReclamo.isSelected()){
            JOptionPane.showMessageDialog(null, "Seleccione solo Uno");               
        }
        if(CheckBoxGarantia.isSelected() && CheckBoxReclamo.isSelected()){
            JOptionPane.showMessageDialog(null, "Seleccione solo Uno");               
        }
        if(CheckBoxGarantia.isSelected()){
            txtServicio.setText("GARANTIA");
        }
        if(CheckBoxReparacion.isSelected()){
            txtServicio.setText("REPARACIÓN");
        }
        if(CheckBoxMantenimento.isSelected()){
            txtServicio.setText("MANTENIMIENTO");
        }
        if(CheckBoxReclamo.isSelected()){
            txtServicio.setText("RECLAMO");
        }
        String Falla_reportada = txtFallaReportada.getText();
        
        //RadioButtons
        if(RadioAntorchaSi.isSelected()){
            txtAntorcha.setText("1");
            System.out.print(txtAntorcha.getText());
        }
        if(RadioAntorchaNo.isSelected()){
            txtAntorcha.setText("0");
            System.out.print(txtAntorcha.getText());            
        }
        if(RadioPortaSi.isSelected()){
            txtPortaElectrodo.setText("1");
        }
        if(RadioPortaNo.isSelected()){
            txtPortaElectrodo.setText("0");
        }
        if(RadioPinzaSi.isSelected()){
            txtPinzaMasa.setText("1");
        }
        if(RadioPinzaNo.isSelected()){
            txtPinzaMasa.setText("0");
        }
        if(RadioCableSi.isSelected()){
            txtCableAcometida.setText("1");
        }
        if(RadioCableNo.isSelected()){
            txtCableAcometida.setText("0");
        }
        if(RadioClavijaSi.isSelected()){
            txtClavija.setText("1");
        }
        if(RadioClavijaNo.isSelected()){
            txtClavija.setText("0");
        }
        if(RadioReguladorSi.isSelected()){
            txtReguladorGas.setText("1");
        }
        if(RadioReguladorNo.isSelected()){
            txtReguladorGas.setText("0");
        }
        if(RadioMangueraSi.isSelected()){
            txtMangueraGas.setText("1");
        }
        if(RadioMangueraNo.isSelected()){
            txtMangueraGas.setText("0");
        }
        if(RadioPernosSi.isSelected()){
            txtPernos.setText("1");
        }
        if(RadioPernosNo.isSelected()){
            txtPernos.setText("0");
        }
        if(RadioRidillosSi.isSelected()){
            txtRidillos.setText("1");
        }
        if(RadioRidillosNo.isSelected()){
            txtRidillos.setText("0");
        }
        if(RadioPerillasSi.isSelected()){
            txtPerillas.setText("1");
        }
        if(RadioPerillasNo.isSelected()){
            txtPerillas.setText("0");
        }
        if(RadioAsasSi.isSelected()){
            txtAsas.setText("1");
        }
        if(RadioAsasNo.isSelected()){
            txtAsas.setText("0");
        }
        if(RadioRuedasSi.isSelected()){
            txtBasedeRuedas.setText("1");
        }
        if(RadioRuedasNo.isSelected()){
            txtBasedeRuedas.setText("0");
        }
        if(RadioCarreteSi.isSelected()){
            txtCarrete.setText("1");
        }
        if(RadioCarreteNo.isSelected()){
            txtCarrete.setText("0");
        }
        if(RadioConsumiblesSi.isSelected()){
            txtConsumibles.setText("1");
        }
        if(RadioConsumiblesNo.isSelected()){
            txtConsumibles.setText("0");
        }
        if(RadioChuponSi.isSelected()){
            txtChupon.setText("1");
        }
        if(RadioChuponNo.isSelected()){
            txtChupon.setText("0");
        }
        if(RadioOtrosSi.isSelected()){
            txtOtros.setText("1");
        }
        if(RadioOtrosNo.isSelected()){
            txtOtros.setText("0");
        }
        String Diagnostico = txtDiagnostico.getText();
        
        //Tabla Orden
        try {
            if (fechaInicio.equals("") || fechaSalida.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar La Fecha");               
            } else {
                String sql = "INSERT INTO orden(fecha_ingreso, fecha_salida) VALUES('" + fechaInicio + "','" + fechaSalida + "')";
                con = cn.getConnection();
                st = con.createStatement();
                st.executeUpdate(sql);

            }

        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo guardar datos"+e);

        }
        //Tabla Cliente
        try {
            if (Nombre.equals("") || Direccion.equals("") || RUC.equals("") || DNI.equals("") || Encargado.equals("") || Telefono.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar Datos");
                               
            } else {
                String sql = "INSERT INTO cliente(Nombre, Direccion, RUC, DNI, Encargado, Telefono, Nro_Orden) VALUES('" + Nombre + "','" + Direccion + "','" + RUC + "','" + DNI + "','" + Encargado + "','" + Telefono + "','" + Nro_Orden + "')";
                con = cn.getConnection();
                st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Registrado con Exito");
                
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar datos"+e);

        }
        //Tabla Soldadora
        try {
            if (Marca.equals("") || Email.equals("") || Modelo.equals("") || Code.equals("") || Horometro.equals("") || Nro_Serie.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar Datos");
                               
            } else {
                String sql = "INSERT INTO `soldadora`(`Marca`, `Modelo`, `Nro_Serie`, `Code`, `Email`, `Horometro`, `Diagnostico`, `Foto_Ingreso`, `Foto_Reparacion`, `Foto_Salida`, `Nro_Orden`) VALUES ('" + Marca + "','" + Modelo + "','" + Nro_Serie + "','" + Code + "','" + Email + "','" + Horometro + "','" + Diagnostico + "','" + 1 + "','" + 2 + "','" + 3 + "')";
                con = cn.getConnection();
                st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Registrado con Exito");
                
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar datos"+e);

        }
        //Tabla Encargado
        try {
            if (Recepcionado_por.equals("") || Falla_reportada.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar Datos");
                               
            } else {
                String sql = "INSERT INTO `encargado`(`Recepcionado_por`, `Servicio`, `Falla_reportada`, `Nro_Orden`) VALUES ('" + Recepcionado_por + "','" + txtServicio.getText() + "','" + Falla_reportada + "')";
                con = cn.getConnection();
                st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Registrado con Exito");
                
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar datos"+e);

        }
         
        try {
            if (RadioAntorchaSi.equals("") || RadioAntorchaNo.equals("")) {
                JOptionPane.showMessageDialog(null, "Debe Marcar Si o No");               
            } else {
                String sql = "INSERT INTO `elementos`(`Antorcha`, `Porta_electrodo`, `pinza_masa`, `cable_acometida`, `clavija`, `regulador_gas`, `manguera_gas`, `pernos`, `ridillos`, `perillas`, `asas`, `base_ruedas`, `carrete`, `consumibles`, `chupon`, `otros`, `Nro_Orden`) VALUES (" + txtAntorcha.getText() + "," + txtPortaElectrodo.getText() + "," + txtPinzaMasa.getText() + "," + txtCableAcometida.getText() + "," + txtClavija.getText() + "," + txtReguladorGas.getText() + "," + txtMangueraGas.getText() + "," + txtPernos.getText() + "," + txtRidillos.getText() + "," + txtPerillas.getText() + "," + txtAsas.getText() + "," + txtBasedeRuedas.getText() + "," + txtCarrete.getText() + "," + txtConsumibles.getText() + "," + txtChupon.getText() + "," + txtOtros.getText() + ")";
                con = cn.getConnection();
                st = con.createStatement();
                st.executeUpdate(sql);

            }

        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo guardar datos"+e);

        }
        
        
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxGarantia;
    private javax.swing.JCheckBox CheckBoxMantenimento;
    private javax.swing.JCheckBox CheckBoxReclamo;
    private javax.swing.JCheckBox CheckBoxReparacion;
    private javax.swing.JLabel LabelAntorcha;
    private javax.swing.JLabel LabelAsas;
    private javax.swing.JLabel LabelBaseRuedas;
    private javax.swing.JLabel LabelCableAcometica;
    private javax.swing.JLabel LabelCarrete;
    private javax.swing.JLabel LabelChupon;
    private javax.swing.JLabel LabelClavija;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelCode;
    private javax.swing.JLabel LabelConsumibles;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelDiagnostico;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelElementos1;
    private javax.swing.JLabel LabelElementos2;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEncargado;
    private javax.swing.JLabel LabelFalla;
    private javax.swing.JLabel LabelFechaIngreso;
    private javax.swing.JLabel LabelFechaSalida;
    private javax.swing.JLabel LabelFotoIngreso;
    private javax.swing.JLabel LabelFotoReparacion;
    private javax.swing.JLabel LabelFotoSalida;
    private javax.swing.JLabel LabelHorometro;
    private javax.swing.JLabel LabelManguera;
    private javax.swing.JLabel LabelMarca;
    private javax.swing.JLabel LabelModelo;
    private javax.swing.JLabel LabelNro;
    private javax.swing.JLabel LabelNroSerie;
    private javax.swing.JLabel LabelOrden;
    private javax.swing.JLabel LabelOtros;
    private javax.swing.JLabel LabelPerillas;
    private javax.swing.JLabel LabelPernos;
    private javax.swing.JLabel LabelPinza;
    private javax.swing.JLabel LabelPlanchado;
    private javax.swing.JLabel LabelPortaElectrodo;
    private javax.swing.JLabel LabelRUC;
    private javax.swing.JLabel LabelReceptor;
    private javax.swing.JLabel LabelReguladorGas;
    private javax.swing.JLabel LabelRidillos;
    private javax.swing.JLabel LabelServicio;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JRadioButton RadioAntorchaNo;
    private javax.swing.JRadioButton RadioAntorchaSi;
    private javax.swing.JRadioButton RadioAsasNo;
    private javax.swing.JRadioButton RadioAsasSi;
    private javax.swing.JRadioButton RadioCableNo;
    private javax.swing.JRadioButton RadioCableSi;
    private javax.swing.JRadioButton RadioCarreteNo;
    private javax.swing.JRadioButton RadioCarreteSi;
    private javax.swing.JRadioButton RadioChuponNo;
    private javax.swing.JRadioButton RadioChuponSi;
    private javax.swing.JRadioButton RadioClavijaNo;
    private javax.swing.JRadioButton RadioClavijaSi;
    private javax.swing.JRadioButton RadioConsumiblesNo;
    private javax.swing.JRadioButton RadioConsumiblesSi;
    private javax.swing.JRadioButton RadioMangueraNo;
    private javax.swing.JRadioButton RadioMangueraSi;
    private javax.swing.JRadioButton RadioOtrosNo;
    private javax.swing.JRadioButton RadioOtrosSi;
    private javax.swing.JRadioButton RadioPerillasNo;
    private javax.swing.JRadioButton RadioPerillasSi;
    private javax.swing.JRadioButton RadioPernosNo;
    private javax.swing.JRadioButton RadioPernosSi;
    private javax.swing.JRadioButton RadioPinzaNo;
    private javax.swing.JRadioButton RadioPinzaSi;
    private javax.swing.JRadioButton RadioPortaNo;
    private javax.swing.JRadioButton RadioPortaSi;
    private javax.swing.JRadioButton RadioReguladorNo;
    private javax.swing.JRadioButton RadioReguladorSi;
    private javax.swing.JRadioButton RadioRidillosNo;
    private javax.swing.JRadioButton RadioRidillosSi;
    private javax.swing.JRadioButton RadioRuedasNo;
    private javax.swing.JRadioButton RadioRuedasSi;
    private javax.swing.JTable TableDiagnostico;
    private javax.swing.JTable TablePlanchado;
    private javax.swing.ButtonGroup botonesantorcha;
    private javax.swing.ButtonGroup botonesasas;
    private javax.swing.ButtonGroup botonesbaseruedas;
    private javax.swing.ButtonGroup botonescableacometida;
    private javax.swing.ButtonGroup botonescarrete;
    private javax.swing.ButtonGroup botoneschupon;
    private javax.swing.ButtonGroup botonesclavija;
    private javax.swing.ButtonGroup botonesconsumibles;
    private javax.swing.ButtonGroup botonesmangueragas;
    private javax.swing.ButtonGroup botonesotros;
    private javax.swing.ButtonGroup botonesperillas;
    private javax.swing.ButtonGroup botonespernos;
    private javax.swing.ButtonGroup botonespinzamasa;
    private javax.swing.ButtonGroup botonesportaelectrodo;
    private javax.swing.ButtonGroup botonesreguladorgas;
    private javax.swing.ButtonGroup botonesridillos;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnReparacion;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel labelIngreso;
    private javax.swing.JLabel labelReparacion;
    private javax.swing.JLabel labelSalida;
    private javax.swing.JTextField txtAntorcha;
    private javax.swing.JTextField txtAsas;
    private javax.swing.JTextField txtBasedeRuedas;
    private javax.swing.JTextField txtCableAcometida;
    private javax.swing.JTextField txtCarrete;
    private javax.swing.JTextField txtChupon;
    private javax.swing.JTextField txtClavija;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtConsumibles;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JTextArea txtFallaReportada;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private com.toedter.calendar.JDateChooser txtFechaSalida;
    private javax.swing.JTextField txtHorometro;
    private javax.swing.JTextField txtMangueraGas;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroOrden;
    private javax.swing.JTextField txtOtros;
    private javax.swing.JTextField txtPerillas;
    private javax.swing.JTextField txtPernos;
    private javax.swing.JTextField txtPinzaMasa;
    private javax.swing.JTextField txtPortaElectrodo;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtReceptor;
    private javax.swing.JTextField txtReguladorGas;
    private javax.swing.JTextField txtRidillos;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txt_NroSerie;
    // End of variables declaration//GEN-END:variables

  
}