/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class RegistroOrden extends javax.swing.JFrame {
    Conexion cn = new Conexion();
    Connection con;
    Statement st;    
    ResultSet rs;

    /**
     * Creates new form RegistroOrden
     */
    public RegistroOrden() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        Nro_Orden();
        sies();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        LabelFechaIngreso = new javax.swing.JLabel();
        txtFechaSalida = new com.toedter.calendar.JDateChooser();
        LabelFechaSalida = new javax.swing.JLabel();
        LabelOrden = new javax.swing.JLabel();
        LabelNro = new javax.swing.JLabel();
        txtNroOrden = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setText("REGISTRAR ORDEN");

        txtFechaIngreso.setDateFormatString("yyyy-MM-dd");

        LabelFechaIngreso.setText("FECHA DE INGRESO:");

        txtFechaSalida.setDateFormatString("yyyy-MM-dd");

        LabelFechaSalida.setText("FECHA DE SALIDA:");

        LabelOrden.setText("ORDEN DE SERVICIO");

        LabelNro.setText("N°");

        txtNroOrden.setEditable(false);
        txtNroOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroOrdenActionPerformed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Volver.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(491, 491, 491)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFechaIngreso)
                            .addComponent(LabelFechaSalida))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189)
                        .addComponent(LabelNro))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LabelOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFechaIngreso)
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFechaSalida)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelOrden)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNro)
                            .addComponent(txtNroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(492, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNroOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroOrdenActionPerformed

    }//GEN-LAST:event_txtNroOrdenActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio Inicio=new Inicio();
        Inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fechaInicio =((JTextField)txtFechaIngreso.getDateEditor().getUiComponent()).getText();
        String fechaSalida =((JTextField)txtFechaSalida.getDateEditor().getUiComponent()).getText();
        
        if(fechaInicio.equals("") || fechaSalida.equals("")){
            JOptionPane.showMessageDialog(null, "Debe Ingresar La Fecha");               
            this.setVisible(true);
        }else{
            Formulario Formulario=new Formulario();
            Formulario.setVisible(true);
            this.setVisible(false);
            Agregarorden();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Inicio Inicio=new Inicio();
        Inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    void Agregarorden() {
        //Orden        
        String fechaInicio =((JTextField)txtFechaIngreso.getDateEditor().getUiComponent()).getText();
        String fechaSalida =((JTextField)txtFechaSalida.getDateEditor().getUiComponent()).getText();
        //Tabla Orden
        try {
            if (fechaInicio.equals("") || fechaSalida.equals("")) {
            } else {
                String sql = "INSERT INTO orden(fecha_ingreso, fecha_salida,Nro_Orden) VALUES('" + fechaInicio + "','" + fechaSalida + "'," + txtNroOrden.getText() + ")";
                con = cn.getConnection();
                st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Orden Registrada");
            }

        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo guardar datos"+e);

        }
        //Tabla Cliente
    }
    void Nro_Orden(){
        String sql = "select Max(Nro_Orden)+1 as Nro_Orden from orden";
        
    try {

        con = cn.getConnection();
        st = con.createStatement();
        rs = st.executeQuery(sql);
        
        while (rs.next ( ))
        {
           String Nro_Orden = rs.getString ("Nro_Orden");
           txtNroOrden.setText(Nro_Orden);

        }        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    void sies(){
        String Nro_Or = txtNroOrden.getText();
            if (Nro_Or.equals("")){
               txtNroOrden.setText("1");
               txtNroOrden.getText();
           }else{
           }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFechaIngreso;
    private javax.swing.JLabel LabelFechaSalida;
    private javax.swing.JLabel LabelNro;
    private javax.swing.JLabel LabelOrden;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private com.toedter.calendar.JDateChooser txtFechaSalida;
    private javax.swing.JTextField txtNroOrden;
    // End of variables declaration//GEN-END:variables
}
